### ISSUE TITLE
Not able to see the metrics inside the log

### ISSUE THREAD

**Issue by xwlee** [avillela/otel-python-lab#3]
I followed the exact steps from the video, but I couldn't see the metrics in the log when running: 

```bash
kubectl logs -l app=opentelemetry -n opentelemetry --follow
```

I'm supposed to see something like the following:

<img width="374" alt="Screenshot 2024-06-20 at 10 44 43 AM" src="https://github.com/avillela/otel-python-lab/assets/688247/2a4114a5-2c4b-4905-9953-20837b587897">

 Anything that I miss?

**Comment by avillela** [comment]
It is usually one of two things:
1. Your terminal buffer might be too small, so that log entry is getting truncated by the time you're doing the search
2. Sometimes it takes a while before it shows up
