### ISSUE TITLE
Can't run setup script due to iptables issue in the kind cluster setup

### ISSUE THREAD

**Issue by hokey** [avillela/otel-python-lab#4]
Hello,

I opened the lab in a codespace and was stapped at the setup script step due to this error:

`Creating cluster "otel-python-lab" ...
ERROR: failed to create cluster: failed to ensure docker network: command "docker network create -d=bridge -o com.docker.network.bridge.enable_ip_masquerade=true -o com.docker.network.driver.mtu=1500 --ipv6 --subnet fc00:f853:ccd:e793::/64 kind" failed with error: exit status 1
Command Output: Error response from daemon: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: ip6tables --wait -t nat -I POSTROUTING -s fc00:f853:ccd:e793::/64 ! -o br-94ab107754dc -j MASQUERADE: ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.`

I'm wondering if something changed with how either kind does that or with how codespaces manages networking.  I'm unsure, can you take a look at it and maybe see if it's reproducible?  Thanks,

-- Mike

**Comment by avillela** [comment]
You're right. I'm totally stumped on this one. I created a Devcontainer for the tutorial lab so you can at least run it locally. Unfortunately it doesn't fix the issue of it not running in Codespaces. I need to investigate the GH Codespaces issue further. If you're running everything locally and you have a Silicon Mac, you'll need to change `amd64` to `arm64` in the setup script.

**Comment by avillela** [comment]
**Update:** I just logged an issue with the KinD folks to see if I can get some traction on this issue: https://github.com/kubernetes-sigs/kind/issues/3748

**Comment by avillela** [comment]
@hokey I put in a workaround that should allow you to run this in GH Codespaces once again: #10

**Comment by hokey** [comment]
@avillela,  thanks!  I was able to get in and continue on!
